version: '3.4'

x-logging:
  &default
  options:
    max-size: '50m'
    max-file: '1'
  driver: json-file

services:
  mirror:
    image: wudder/docs
    container_name: wudder-docs
    volumes:
      - ./docs:/var/docsify/docs:ro
    ports:
      - 80:3000
    logging: *default